import os
import sys

path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'lib'))

sys.path.insert(1, os.path.join(path, 'web'))
sys.path.insert(1, os.path.join(path, 'geojson-1.0'))
sys.path.insert(1, os.path.join(path, 'pyshp'))
sys.path.insert(1, os.path.join(path, 'fastkml-0.5'))
sys.path.insert(1, os.path.join(path, 'pygeoif-0.4.1'))
sys.path.insert(1, os.path.join(path, 'beautifulSoup'))
sys.path.insert(1, os.path.join(path, 'markdown'))
sys.path.insert(1, os.path.join(path, 'python-dateutil-2.0'))
sys.path.insert(1, os.path.join(path, 'cloudstorage'))
sys.path.insert(1, os.path.join(path, 'stripe'))
sys.path.insert(1, os.path.join(path, 'tzlocal'))
sys.path.insert(1, os.path.join(path, 'pytz'))
sys.path.insert(1, os.path.join(path, 'geohash'))
sys.path.insert(1, os.path.join(path, 'xlrd-0.6.1'))
sys.path.insert(1, os.path.join(path, 'oauth2'))
sys.path.insert(1, os.path.join(path, 'httplib', 'python2'))
sys.path.insert(1, os.path.join(path, 'premailer'))
sys.path.insert(1, os.path.join(path, 'cssselect'))
sys.path.insert(1, os.path.join(path, 'cssutils-pip'))
sys.path.insert(1, os.path.join(path, 'werkzeug'))
sys.path.insert(1, os.path.join(path, 'itsdangerous'))
sys.path.insert(1, os.path.join(path, 'flask'))
sys.path.insert(1, os.path.join(path, 'pipeline'))
sys.path.insert(1, os.path.join(path, 'gcs'))
sys.path.insert(1, os.path.join(path, 'pytz'))
sys.path.insert(1, os.path.join(path, 'tzlocal'))
sys.path.insert(1, os.path.join(path, 'httplib2/python2'))
sys.path.insert(1, os.path.join(path, 'oauth2client-1.2'))
sys.path.insert(1, os.path.join(path, 'google-api-python-client-1.2'))
sys.path.insert(1, os.path.join(path, 'pymongo-2.9.2'))
sys.path.insert(1, os.path.join(path, 'googledatastore-v1beta2-rev1-2.1.0'))
sys.path.insert(1, os.path.join(path, 'pyparsing-2.0.7'))
sys.path.insert(1, os.path.join(path, 'cssutils-1.0.1', 'src'))
sys.path.insert(1, os.path.join(path, 'unidecode'))
sys.path.insert(1, os.path.join(path, 'urllib3'))
sys.path.insert(1, os.path.join(path, 'elasticsearch'))

